import '../models/food_model.dart';

class FoodDatabase {
  static final Map<String, FoodModel> foods = {
    'adobong_atay': FoodModel(
      id: 'adobong_atay',
      imageUrl: 'assets/images/food/adobong_atay.jpg',
      localNames: ["Atay Adobo"],
      name: 'Adobong Atay',
      ingredients: [
        'Chicken Liver',
        'Soy Sauce',
        'Vinegar',
        'Garlic',
        'Bay Leaf',
        'Pepper'
      ],
    ),
    'adobong_manok': FoodModel(
        id: 'adobong_manok',
        imageUrl: 'assets/images/food/adobong_manok.jpg',
        localNames: ["Atay Adobo"],
        name: 'Adobong Manok',
        ingredients: [
          'Chicken',
          'Soy Sauce',
          'Vinegar',
          'Garlic',
          'Bay Leaf',
          'Pepper'
        ]),
    'adobong_pusit': FoodModel(
      id: 'adobong_pusit',
      imageUrl: 'assets/images/food/adobong_pusit.jpg',
      localNames: ["Pusit Adobo"],
      name: 'Adobong Pusit',
      ingredients: [
        'Squid',
        'Soy Sauce',
        'Vinegar',
        'Garlic',
        'Onion',
        'Squid Ink'
      ],
    ),
    'adobong_sitaw': FoodModel(
      id: 'adobong_sitaw',
      imageUrl: 'assets/images/food/adobong_sitaw.jpg',
      localNames: ["Sitaw Adobo"],
      name: 'Adobong Sitaw',
      ingredients: ['String Beans', 'Soy Sauce', 'Vinegar', 'Garlic'],
    ),
    'ampalaya_with_egg': FoodModel(
      id: 'ampalaya_with_egg',
      imageUrl: 'assets/images/food/ampalaya_with_egg.jpg',
      localNames: ["Ginisang Ampalaya at Itlog"],
      name: 'Ampalaya with Egg',
      ingredients: ['Bitter Melon', 'Eggs', 'Onion', 'Garlic', 'Oil'],
    ),
    'arroz_caldo': FoodModel(
      id: 'arroz_caldo',
      imageUrl: 'assets/images/food/arroz_caldo.jpg',
      localNames: ["Lugaw", "Goto"],
      name: 'Arroz Caldo',
      ingredients: [
        'Rice',
        'Chicken',
        'Ginger',
        'Garlic',
        'Onion',
        'Fish Sauce'
      ],
    ),
    'atay_na_barbecue': FoodModel(
      id: 'atay_na_barbecue',
      imageUrl: 'assets/images/food/atay_na_barbecue.jpg',
      localNames: ["Inihaw na Atay"],
      name: 'Atay na Barbecue',
      ingredients: [
        'Chicken Liver',
        'Soy Sauce',
        'Banana Ketchup',
        'Sugar',
        'Garlic'
      ],
    ),
    'atsara': FoodModel(
      id: 'atsara',
      imageUrl: 'assets/images/food/atsara.jpg',
      localNames: ["Achara"],
      name: 'Atsara (Pickled Papaya)',
      ingredients: [
        'Green Papaya',
        'Vinegar',
        'Sugar',
        'Carrots',
        'Bell Pepper',
        'Raisins'
      ],
    ),
    'baklava': FoodModel(
      id: 'baklava',
      imageUrl: 'assets/images/food/baklava.jpg',
      name: 'Baklava',
      ingredients: [
        'Phyllo Dough',
        'Walnuts',
        'Butter',
        'Honey',
        'Sugar Syrup'
      ],
    ),
    'balot': FoodModel(
      id: 'balot',
      imageUrl: 'assets/images/food/balot.jpg',
      localNames: ["Balut"],
      name: 'Balot',
      ingredients: ['Fertilized Duck Egg', 'Salt'],
    ),
    'banana_cue': FoodModel(
      id: 'banana_cue',
      imageUrl: 'assets/images/food/banana_cue.jpg',
      name: 'Banana Cue',
      localNames: ["Banana Kue", "Saging na Minatamis"],
      ingredients: ['Saba Banana', 'Brown Sugar', 'Cooking Oil'],
    ),
    'banana_nut_cake': FoodModel(
      id: 'banana_nut_cake',
      imageUrl: 'assets/images/food/banana_nut_cake.jpg',
      name: 'Banana Nut Cake',
      ingredients: ['Banana', 'Flour', 'Eggs', 'Sugar', 'Butter', 'Nuts'],
    ),
    'bangus_sisig': FoodModel(
      id: 'bangus_sisig',
      imageUrl: 'assets/images/food/bangus_sisig.jpg',
      name: 'Bangus Sisig',
      localNames: ["Sisig na Bangus"],
      ingredients: ['Milkfish', 'Onion', 'Calamansi', 'Chili', 'Mayonnaise'],
    ),
    'batikon': FoodModel(
      id: 'batikon',
      imageUrl: 'assets/images/food/batikon.jpg',
      name: 'Batikon',
      localNames: ["Batirol"],
      ingredients: ['Rice Flour', 'Sugar', 'Coconut Milk'],
    ),
    'beef_chicken_shawarma': FoodModel(
      id: 'beef_chicken_shawarma',
      imageUrl: 'assets/images/food/beef_chicken_shawarma.jpg',
      name: 'Beef and Chicken Shawarma',
      ingredients: ['Beef', 'Chicken', 'Pita Bread', 'Garlic Sauce', 'Spices'],
    ),
    'beef_bulalo': FoodModel(
      id: 'beef_bulalo',
      localNames: ["Bulalong Baka"],
      imageUrl: 'assets/images/food/beef_bulalo.jpg',
      name: 'Beef Bulalo',
      ingredients: ['Beef Shank', 'Corn', 'Cabbage', 'Peppercorn', 'Onion'],
    ),
    'beef_kaldereta': FoodModel(
      id: 'beef_kaldereta',
      imageUrl: 'assets/images/food/beef_kaldereta.jpg',
      localNames: ["Kalderetang Baka"],
      name: 'Beef Kaldereta',
      ingredients: [
        'Beef',
        'Tomato Sauce',
        'Potatoes',
        'Carrots',
        'Bell Pepper'
      ],
    ),
    'beef_tacos': FoodModel(
      id: 'beef_tacos',
      imageUrl: 'assets/images/food/beef_tacos.jpg',
      name: 'Beef Tacos',
      ingredients: ['Ground Beef', 'Tortilla', 'Lettuce', 'Cheese', 'Tomato'],
    ),
    'bibingka': FoodModel(
      id: 'bibingka',
      imageUrl: 'assets/images/food/bibingka.jpg',
      name: 'Bibingka',
      localNames: ["Bibingkang Kanin"],
      ingredients: ['Rice Flour', 'Coconut Milk', 'Egg', 'Sugar', 'Salted Egg'],
    ),
    'bicol_express_bagoong': FoodModel(
      id: 'bicol_express_bagoong',
      localNames: ["Sinilihan"],
      imageUrl: 'assets/images/food/bicol_express_bagoong.jpg',
      name: 'Bicol Express with Bagoong',
      ingredients: ['Pork', 'Coconut Milk', 'Chili', 'Shrimp Paste', 'Garlic'],
    ),
    'bicol_express_no_bagoong': FoodModel(
      id: 'bicol_express_no_bagoong',
      imageUrl: 'assets/images/food/bicol_express_no_bagoong.jpg',
      localNames: ["Laing na Baboy"],
      name: 'Bicol Express without Bagoong',
      ingredients: ['Pork', 'Coconut Milk', 'Chili', 'Garlic'],
    ),
    'biko': FoodModel(
      id: 'biko',
      imageUrl: 'assets/images/food/biko.jpg',
      name: 'Biko',
      localNames: ["Sinukmani"],
      ingredients: ['Glutinous Rice', 'Coconut Milk', 'Brown Sugar'],
    ),
    'buko_pie': FoodModel(
      id: 'buko_pie',
      imageUrl: 'assets/images/food/buko_pie.jpg',
      name: 'Buko Pie',
      ingredients: ['Young Coconut', 'Flour', 'Butter', 'Sugar', 'Milk'],
    ),
    'cassava_cake': FoodModel(
      id: 'cassava_cake',
      imageUrl: 'assets/images/food/cassava_cake.jpg',
      name: 'Cassava Cake',
      localNames: ["Bibingkang Kamoteng Kahoy"],
      ingredients: ['Grated Cassava', 'Coconut Milk', 'Condensed Milk', 'Egg'],
    ),
    'cay_cay': FoodModel(
      id: 'cay_cay',
      imageUrl: 'assets/images/food/cay_cay.jpg',
      localNames: ["Karioka"],
      name: 'Cay-Cay',
      ingredients: ['Glutinous Rice', 'Sugar', 'Oil'],
    ),
    'champorado': FoodModel(
      id: 'champorado',
      imageUrl: 'assets/images/food/champorado.jpg',
      localNames: ["Tsampurado"],
      name: 'Champorado',
      ingredients: ['Rice', 'Cocoa Powder', 'Sugar', 'Milk'],
    ),
    'chop_suey_with_egg': FoodModel(
      id: 'chop_suey_with_egg',
      imageUrl: 'assets/images/food/chop_suey_with_egg.jpg',
      name: 'Chop Suey with Egg',
      localNames: ["Chopsuey"],
      ingredients: ['Mixed Vegetables', 'Egg', 'Garlic', 'Soy Sauce'],
    ),
    'chicken_curry': FoodModel(
      id: 'chicken_curry',
      imageUrl: 'assets/images/food/chicken_curry.jpg',
      localNames: ["Kare-Kareng Manok"],
      name: 'Chicken Curry',
      ingredients: [
        'Chicken',
        'Coconut Milk',
        'Curry Powder',
        'Potatoes',
        'Carrots'
      ],
    ),
    'chicken_feet_adobo': FoodModel(
      id: 'chicken_feet_adobo',
      imageUrl: 'assets/images/food/chicken_feet_adobo.jpg',
      localNames: ["Adobong Adidas"],
      name: 'Chicken Feet Adobo',
      ingredients: ['Chicken Feet', 'Soy Sauce', 'Vinegar', 'Garlic'],
    ),
    'chicken_halal_samosa': FoodModel(
      id: 'chicken_halal_samosa',
      imageUrl: 'assets/images/food/chicken_halal_samosa.jpg',
      name: 'Chicken Halal Samosa',
      ingredients: ['Chicken', 'Flour', 'Onion', 'Spices'],
    ),
    'chicken_pastil': FoodModel(
      id: 'chicken_pastil',
      imageUrl: 'assets/images/food/chicken_pastil.jpg',
      localNames: ["Pastil"],
      name: 'Chicken Pastil',
      ingredients: ['Chicken', 'Rice', 'Soy Sauce', 'Garlic'],
    ),
    'chocolate_moron': FoodModel(
      id: 'chocolate_moron',
      imageUrl: 'assets/images/food/chocolate_moron.jpg',
      name: 'Chocolate Moron',
      localNames: ["Morón"],
      ingredients: ['Rice Flour', 'Cocoa Powder', 'Coconut Milk', 'Sugar'],
    ),
    'cuchinta': FoodModel(
      id: 'cuchinta',
      imageUrl: 'assets/images/food/cuchinta.jpg',
      name: 'Cuchinta',
      localNames: ["Kutsinta"],
      ingredients: ['Rice Flour', 'Brown Sugar', 'Lye Water'],
    ),
    'betamax': FoodModel(
      id: 'betamax',
      imageUrl: 'assets/images/food/betamax.jpg',
      name: 'Betamax',
      localNames: ["Inihaw na Dugo"],
      ingredients: ['Chicken Blood', 'Vinegar', 'Garlic'],
    ),
    'kwek_kwek': FoodModel(
      id: 'kwek_kwek',
      imageUrl: 'assets/images/food/kwek_kwek.jpg',
      name: 'Kwek Kwek',
      localNames: ["Tokneneng"],
      ingredients: ['Quail Eggs', 'Flour', 'Annatto', 'Oil'],
    ),
    'escabitchi': FoodModel(
      id: 'escabitchi',
      imageUrl: 'assets/images/food/escabitchi.jpg',
      name: 'Escabitchi',
      localNames: ["Escabeche"],
      ingredients: ['Fish', 'Vinegar', 'Onion', 'Bell Pepper'],
    ),
    'fishball': FoodModel(
      id: 'fishball',
      imageUrl: 'assets/images/food/fishball.jpg',
      name: 'Fishball',
      localNames: ["Bola-Bola ng Isda"],
      ingredients: ['Fish Paste', 'Flour', 'Garlic', 'Salt'],
    ),
    'ginataang_nangka': FoodModel(
      id: 'ginataang_nangka',
      imageUrl: 'assets/images/food/ginataang_nangka.jpg',
      name: 'Ginataang Nangka',
      localNames: ["Nangkang Gata"],
      ingredients: ['Young Jackfruit', 'Coconut Milk', 'Garlic', 'Shrimp'],
    ),
    'ginataang_tilapia': FoodModel(
      id: 'ginataang_tilapia',
      imageUrl: 'assets/images/food/ginataang_tilapia.jpg',
      name: 'Ginataang Tilapia',
      localNames: ["Tilapia sa Gata"],
      ingredients: ['Tilapia', 'Coconut Milk', 'Ginger', 'Garlic'],
    ),
    'ginisang_ampalaya': FoodModel(
      id: 'ginisang_ampalaya',
      imageUrl: 'assets/images/food/ginisang_ampalaya.jpg',
      name: 'Ginisang Ampalaya',
      localNames: ["Ampalaya Guisado"],
      ingredients: ['Bitter Melon', 'Egg', 'Onion', 'Garlic'],
    ),
    'ginataang_hipon': FoodModel(
      id: 'ginataang_hipon',
      imageUrl: 'assets/images/food/ginataang_hipon.jpg',
      name: 'Ginataang Hipon',
      localNames: ["Hipon sa Gata"],
      ingredients: ['Shrimp', 'Coconut Milk', 'Garlic', 'Chili'],
    ),
    'grilled_chicken_liver': FoodModel(
      id: 'grilled_chicken_liver',
      imageUrl: 'assets/images/food/grilled_chicken_liver.jpg',
      name: 'Grilled Chicken Liver',
      localNames: ["Inihaw na Atay ng Manok"],
      ingredients: ['Chicken Liver', 'Salt', 'Pepper'],
    ),
    'grilled_shrimp': FoodModel(
      id: 'grilled_shrimp',
      imageUrl: 'assets/images/food/grilled_shrimp.jpg',
      name: 'Grilled Shrimp',
      localNames: ["Inihaw na Hipon"],
      ingredients: ['Shrimp', 'Garlic', 'Butter'],
    ),
    'halang_halang': FoodModel(
      id: 'halang_halang',
      imageUrl: 'assets/images/food/halang_halang.jpg',
      name: 'Halang-Halang',
      localNames: ["Halang-Halang na Manok"],
      ingredients: ['Chicken', 'Coconut Milk', 'Chili', 'Ginger'],
    ),
    'halo_halo': FoodModel(
      id: 'halo_halo',
      imageUrl: 'assets/images/food/halo_halo.jpg',
      name: 'Halo-Halo',
      ingredients: ['Shaved Ice', 'Milk', 'Sweet Beans', 'Fruits', 'Ice Cream'],
    ),
    'inulukan': FoodModel(
      id: 'inulukan',
      imageUrl: 'assets/images/food/inulukan.jpg',
      name: 'Inulukan',
      ingredients: ['Crab Meat', 'Coconut Milk', 'Garlic'],
    ),
    'isaw': FoodModel(
      id: 'isaw',
      imageUrl: 'assets/images/food/isaw.jpg',
      name: 'Isaw',
      localNames: ["Inihaw na Isaw"],
      ingredients: ['Chicken Intestines', 'Vinegar', 'Garlic'],
    ),
    'kalamay': FoodModel(
      id: 'kalamay',
      imageUrl: 'assets/images/food/kalamay.jpg',
      name: 'Kalamay (Ube flavor)',
      localNames: ["Kalamay Ube"],
      ingredients: ['Glutinous Rice Flour', 'Coconut Milk', 'Sugar', 'Ube'],
    ),
    'kapampangan_bopis': FoodModel(
      id: 'kapampangan_bopis',
      imageUrl: 'assets/images/food/kapampangan_bopis.jpg',
      name: 'Kapampangan Bopis',
      localNames: ["Bopis"],
      ingredients: ['Pork Lungs', 'Vinegar', 'Garlic', 'Chili'],
    ),
    'pork_kare_kare': FoodModel(
      id: 'pork_kare_kare',
      imageUrl: 'assets/images/food/pork_kare_kare.jpg',
      localNames: ["Kare-Kareng Baboy"],
      name: 'Pork Kare-Kare',
      ingredients: ['Pork', 'Peanut Sauce', 'Eggplant', 'String Beans'],
    ),
    'kikiam': FoodModel(
      id: 'kikiam',
      imageUrl: 'assets/images/food/kikiam.jpg',
      name: 'Kikiam',
      localNames: ["Quekiam"],
      ingredients: ['Ground Pork', 'Flour Wrapper', 'Garlic'],
    ),
    'kinilaw_tuna_gata': FoodModel(
      id: 'kinilaw_tuna_gata',
      imageUrl: 'assets/images/food/kinilaw_tuna_gata.jpg',
      name: 'Kinilaw na Tuna sa Gata',
      localNames: ["Kilawin na Tuna"],
      ingredients: ['Fresh Tuna', 'Vinegar', 'Coconut Milk', 'Ginger'],
    ),
    'laing': FoodModel(
      id: 'laing',
      imageUrl: 'assets/images/food/laing.jpg',
      name: 'Laing Bicol Express',
      localNames: ["Pinangat"],
      ingredients: ['Dried Taro Leaves', 'Coconut Milk', 'Chili', 'Pork'],
    ),
    'lasagna': FoodModel(
      id: 'lasagna',
      imageUrl: 'assets/images/food/lasagna.jpg',
      name: 'Lasagna',
      ingredients: ['Lasagna Noodles', 'Ground Beef', 'Tomato Sauce', 'Cheese'],
    ),
    'lokot_lokot': FoodModel(
      id: 'lokot_lokot',
      imageUrl: 'assets/images/food/lokot_lokot.jpg',
      name: 'Lokot-Lokot',
      localNames: ["Amik"],
      ingredients: ['Rice Flour', 'Sugar', 'Oil'],
    ),
    'maja_blanca': FoodModel(
      id: 'maja_blanca',
      imageUrl: 'assets/images/food/maja_blanca.jpg',
      localNames: ["Maja"],
      name: 'Maja Blanca',
      ingredients: ['Coconut Milk', 'Cornstarch', 'Sugar', 'Corn'],
    ),
    'menudo': FoodModel(
      id: 'menudo',
      imageUrl: 'assets/images/food/menudo.jpg',
      localNames: ["Menudong Baboy"],
      name: 'Menudo',
      ingredients: ['Pork', 'Tomato Sauce', 'Potatoes', 'Carrots'],
    ),
    'niliggid': FoodModel(
      id: 'niliggid',
      imageUrl: 'assets/images/food/niliggid.jpg',
      name: 'Niliggid',
      ingredients: ['Sticky Rice', 'Coconut Milk', 'Sugar'],
    ),
    'paklay': FoodModel(
      id: 'paklay',
      imageUrl: 'assets/images/food/paklay.jpg',
      name: 'Paklay',
      ingredients: ['Goat Meat', 'Pineapple', 'Vinegar', 'Garlic'],
    ),
    'pancit_bihon': FoodModel(
      id: 'pancit_bihon',
      imageUrl: 'assets/images/food/pancit_bihon.jpg',
      localNames: ["Pansit Bihon"],
      name: 'Pancit Bihon',
      ingredients: ['Rice Noodles', 'Chicken', 'Vegetables', 'Soy Sauce'],
    ),
    'pancit_malabon': FoodModel(
      id: 'pancit_malabon',
      imageUrl: 'assets/images/food/pancit_malabon.jpg',
      localNames: ["Pansit Malabon"],
      name: 'Pancit Malabon',
      ingredients: ['Thick Rice Noodles', 'Shrimp', 'Squid', 'Egg'],
    ),
    'picalong': FoodModel(
      id: 'picalong',
      imageUrl: 'assets/images/food/picalong.jpg',
      name: 'Picalong',
      ingredients: ['Sticky Rice', 'Coconut Milk', 'Sugar'],
    ),
    'pichi_pichi': FoodModel(
      id: 'pichi_pichi',
      imageUrl: 'assets/images/food/pichi_pichi.jpg',
      name: 'Pichi-Pichi',
      localNames: ["Pitsí-pitsí"],
      ingredients: ['Cassava', 'Sugar', 'Lye Water', 'Coconut'],
    ),
    'pickled_coconut': FoodModel(
      id: 'pickled_coconut',
      imageUrl: 'assets/images/food/pickled_coconut.jpg',
      name: 'Pickled Coconut',
      localNames: ["Buro na Niyog"],
      ingredients: ['Young Coconut', 'Vinegar', 'Sugar'],
    ),
    'pinakbet': FoodModel(
      id: 'pinakbet',
      imageUrl: 'assets/images/food/pinakbet.jpg',
      name: 'Pinakbet',
      localNames: ["Pakbet"],
      ingredients: ['Mixed Vegetables', 'Shrimp Paste', 'Pork'],
    ),
    'piyanggang_manok': FoodModel(
      id: 'piyanggang_manok',
      imageUrl: 'assets/images/food/piyanggang_manok.jpg',
      name: 'Piyanggang Manok',
      ingredients: ['Chicken', 'Burnt Coconut', 'Ginger', 'Turmeric'],
    ),
    'piyaya_piaya': FoodModel(
      id: 'piyaya_piaya',
      imageUrl: 'assets/images/food/piyaya_piaya.jpg',
      name: 'Piyaya-Piaya',
      localNames: ["Piyaya"],
      ingredients: ['Flour', 'Sugar', 'Butter'],
    ),
    'pochero': FoodModel(
      id: 'pochero',
      imageUrl: 'assets/images/food/pochero.jpg',
      name: 'Pochero',
      localNames: ["Putsero"],
      ingredients: ['Beef', 'Banana', 'Tomato Sauce', 'Potatoes'],
    ),
    'pork_dinuguan': FoodModel(
      id: 'pork_dinuguan',
      imageUrl: 'assets/images/food/pork_dinuguan.jpg',
      name: 'Pork Dinuguan',
      localNames: ["Dinardaraan"],
      ingredients: ['Pork', 'Pork Blood', 'Vinegar', 'Garlic'],
    ),
    'pork_embutido': FoodModel(
      id: 'pork_embutido',
      imageUrl: 'assets/images/food/pork_embutido.jpg',
      name: 'Pork Embutido',
      localNames: ["Embutido"],
      ingredients: ['Ground Pork', 'Egg', 'Raisins', 'Carrots'],
    ),
    'pork_humba': FoodModel(
      id: 'pork_humba',
      imageUrl: 'assets/images/food/pork_humba.jpg',
      name: 'Pork Humba',
      localNames: ["Humba"],
      ingredients: ['Pork Belly', 'Soy Sauce', 'Brown Sugar', 'Banana Blossom'],
    ),
    'pork_sinigang': FoodModel(
      id: 'pork_sinigang',
      imageUrl: 'assets/images/food/pork_sinigang.jpg',
      localNames: ["Sinigang na Baboy"],
      name: 'Pork Sinigang',
      ingredients: ['Pork', 'Tamarind', 'Tomato', 'Vegetables'],
    ),
    'pork_steak': FoodModel(
      id: 'pork_steak',
      imageUrl: 'assets/images/food/pork_steak.jpg',
      localNames: ["Bistek na Baboy"],
      name: 'Pork Steak',
      ingredients: ['Pork Chop', 'Soy Sauce', 'Calamansi', 'Onion'],
    ),
    'puto_bumbong': FoodModel(
      id: 'puto_bumbong',
      imageUrl: 'assets/images/food/puto_bumbong.jpg',
      name: 'Puto Bumbong',
      ingredients: ['Purple Rice', 'Coconut', 'Sugar'],
    ),
    'puto_cheese': FoodModel(
      id: 'puto_cheese',
      imageUrl: 'assets/images/food/puto_cheese.jpg',
      name: 'Puto Cheese',
      localNames: ["Puto Keso"],
      ingredients: ['Rice Flour', 'Sugar', 'Cheese'],
    ),
    'rice_suman': FoodModel(
      id: 'rice_suman',
      imageUrl: 'assets/images/food/rice_suman.jpg',
      name: 'Rice Suman',
      localNames: ["Suman sa Kanin"],
      ingredients: ['Glutinous Rice', 'Coconut Milk', 'Salt'],
    ),
    'salad_crab': FoodModel(
      id: 'salad_crab',
      imageUrl: 'assets/images/food/salad_crab.jpg',
      name: 'Salad Crab',
      localNames: ["Crabstick Salad"],
      ingredients: ['Crab Meat', 'Mayonnaise', 'Lettuce'],
    ),
    'salvaro': FoodModel(
      id: 'salvaro',
      imageUrl: 'assets/images/food/salvaro.jpg',
      name: 'Salvaro',
      localNames: ["Salbaro"],
      ingredients: ['Rice Flour', 'Sugar', 'Coconut Milk', 'Cassava'],
    ),
    'sambulawan': FoodModel(
      id: 'sambulawan',
      imageUrl: 'assets/images/food/sambulawan.jpg',
      name: 'Sambulawan',
      ingredients: ['Beef', 'Curry Powder', 'Cumin Powder', 'Coconut Milk'],
    ),
    'sapin_sapin': FoodModel(
      id: 'sapin_sapin',
      imageUrl: 'assets/images/food/sapin_sapin.jpg',
      name: 'Sapin-Sapin',
      ingredients: ['Rice Flour', 'Coconut Milk', 'Sugar', 'Ube'],
    ),
    'sea_urchin': FoodModel(
      id: 'sea_urchin',
      imageUrl: 'assets/images/food/sea_urchin.jpg',
      localNames: ["Maritangtang"],
      name: 'Sea Urchin',
      ingredients: ['Sea Urchin Roe'],
    ),
    'seaweed_salad': FoodModel(
      id: 'seaweed_salad',
      imageUrl: 'assets/images/food/seaweed_salad.jpg',
      name: 'Seaweed Salad',
      localNames: ["Lato Salad", "Guso Salad"],
      ingredients: ['Seaweed', 'Vinegar', 'Onion'],
    ),
    'spaghetti': FoodModel(
      id: 'spaghetti',
      imageUrl: 'assets/images/food/spaghetti.jpg',
      name: 'Spaghetti',
      localNames: ["Filipino-style Spaghetti"],
      ingredients: ['Pasta', 'Tomato Sauce', 'Ground Meat', 'Cheese'],
    ),
    'calamares': FoodModel(
      id: 'calamares',
      imageUrl: 'assets/images/food/calamares.jpg',
      name: 'Calamares',
      ingredients: ['Squid', 'Flour', 'Egg', 'Oil'],
    ),
    'sundot_kulangot': FoodModel(
      id: 'sundot_kulangot',
      imageUrl: 'assets/images/food/sundot_kulangot.jpg',
      name: 'Sundot Kulangot',
      ingredients: ['Brown Sugar', 'Coconut Milk'],
    ),
    'sweet_sour_fillet': FoodModel(
      id: 'sweet_sour_fillet',
      imageUrl: 'assets/images/food/sweet_sour_fillet.jpg',
      name: 'Sweet and Sour Fillet',
      localNames: ["Escabeche Fillet"],
      ingredients: ['Fish Fillet', 'Vinegar', 'Sugar', 'Bell Pepper'],
    ),
    'tinolang_bangus': FoodModel(
      id: 'tinolang_bangus',
      imageUrl: 'assets/images/food/tinolang_bangus.jpg',
      name: 'Tinolang Bangus',
      localNames: ["Bangus Tinola"],
      ingredients: ['Milkfish', 'Ginger', 'Papaya', 'Fish Sauce'],
    ),
    'tinolang_manok': FoodModel(
      id: 'tinolang_manok',
      imageUrl: 'assets/images/food/tinolang_manok.jpg',
      name: 'Tinolang Manok',
      localNames: ["Manok Tinola"],
      ingredients: ['Chicken', 'Ginger', 'Papaya', 'Fish Sauce'],
    ),
    'tortang_dilis': FoodModel(
      id: 'tortang_dilis',
      imageUrl: 'assets/images/food/tortang_dilis.jpg',
      name: 'Tortang Dilis',
      localNames: ["Dilis Omelette"],
      ingredients: ['Anchovies', 'Egg', 'Oil'],
    ),
    'tortang_okra': FoodModel(
      id: 'tortang_okra',
      imageUrl: 'assets/images/food/tortang_okra.jpg',
      name: 'Tortang Okra',
      localNames: ["Okra Omelette"],
      ingredients: ['Okra', 'Egg', 'Oil'],
    ),
    'tortilla_de_patatas': FoodModel(
      id: 'tortilla_de_patatas',
      imageUrl: 'assets/images/food/tortilla_de_patatas.jpg',
      name: 'Tortilla De Patatas',
      ingredients: ['Potatoes', 'Egg', 'Olive Oil'],
    ),
    'tuna_kilawin': FoodModel(
      id: 'tuna_kilawin',
      imageUrl: 'assets/images/food/tuna_kilawin.jpg',
      name: 'Tuna Kilawin',
      localNames: ["Kinilaw na Tuna"],
      ingredients: ['Fresh Tuna', 'Vinegar', 'Onion', 'Ginger'],
    ),
    'non_food': FoodModel(
      id: 'non_food',
      imageUrl: 'assets/images/food/non_food.jpg',
      name: 'Non Food',
      ingredients: [],
    ),
    'otap': FoodModel(
      id: 'otap',
      imageUrl: 'assets/images/food/otap.jpg',
      name: 'Otap',
      ingredients: ['Flour', 'Sugar', 'Butter'],
    ),
    'lechon_baboy': FoodModel(
      id: 'lechon_baboy',
      imageUrl: 'assets/images/food/lechon_baboy.jpg',
      name: 'Letchon Baboy',
      localNames: ["Lechon"],
      ingredients: ['Whole Pig', 'Salt', 'Spices'],
    ),
    'taho': FoodModel(
      id: 'taho',
      imageUrl: 'assets/images/food/taho.jpg',
      name: 'Taho',
      ingredients: ['Silken Tofu', 'Arnibal', 'Sago Pearls'],
    ),
    'tortang_talong': FoodModel(
      id: 'tortang_talong',
      imageUrl: 'assets/images/food/tortang_talong.jpg',
      name: 'Tortang Talong',
      localNames: ["Talong Omelette"],
      ingredients: ['Eggplant', 'Egg', 'Oil'],
    ),
    'pork_sisig': FoodModel(
      id: 'pork_sisig',
      imageUrl: 'assets/images/food/pork_sisig.jpg',
      name: 'Pork Sisig',
      localNames: ["Sisig"],
      ingredients: ['Pork', 'Onion', 'Calamansi', 'Chili'],
    ),
    'sinigang_na_hipon': FoodModel(
      id: 'sinigang_na_hipon',
      imageUrl: 'assets/images/food/sinigang_na_hipon.jpg',
      name: 'Sinigang na Hipon',
      localNames: ["Hipon Sinigang"],
      ingredients: ['Shrimp', 'Tamarind', 'Vegetables'],
    ),
    'dried_mango': FoodModel(
      id: 'dried_mango',
      imageUrl: 'assets/images/food/dried_mango.jpg',
      name: 'Dried Mango',
      localNames: ["Pinatuyong Mangga"],
      ingredients: ['Mango', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
    'dried_papaya': FoodModel(
      id: 'dried_papaya',
      localNames: ["Pinatuyong Papaya"],
      imageUrl: 'assets/images/food/dried_papaya.jpg',
      name: 'Dried Papaya',
      ingredients: ['Papaya', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
    'dried_pineapple': FoodModel(
      id: 'dried_pineapple',
      localNames: ["Pinatuyong Pinya"],
      imageUrl: 'assets/images/food/dried_pineapple.jpg',
      name: 'Dried Pineapple',
      ingredients: ['Pineapple', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
    'dried_jackfruit': FoodModel(
      id: 'dried_jackfruit',
      imageUrl: 'assets/images/food/dried_jackfruit.jpg',
      localNames: ["Pinatuyong Langka"],
      name: 'Dried Jackfruit',
      ingredients: ['Jackfruit', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
    'dried_coconut': FoodModel(
      id: 'dried_coconut',
      imageUrl: 'assets/images/food/dried_coconut.jpg',
      name: 'Dried Coconut',
      localNames: ["Pinatuyong Niyog"],
      ingredients: ['Coconut', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
    'dried_banana': FoodModel(
      id: 'dried_banana',
      imageUrl: 'assets/images/food/dried_banana.jpg',
      localNames: ["Pinatuyong Saging"],
      name: 'Dried Banana',
      ingredients: ['Banana', 'Sugar', 'Citric Acid', 'Sulfur Dioxide'],
    ),
  };

  static FoodModel? getFoodById(String id) {
    return foods[id];
  }

  static List<FoodModel> getAllFoods() {
    return foods.values.toList();
  }

  static FoodModel? getFoodByName(String name) {
    final cleanName = name.toLowerCase().trim();

    for (var food in foods.values) {
      // check main name
      if (food.name.toLowerCase().trim() == cleanName) {
        return food;
      }

      // check local names (if any)
      if (food.localNames != null && food.localNames!.isNotEmpty) {
        for (final localName in food.localNames!) {
          if (localName.toLowerCase().trim() == cleanName) {
            return food;
          }
        }
      }
    }

    return null;
  }
}
